framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'
        envelope:
            sender: 'no-reply@pagnylablanchecote.net'
            recipients: ['mairie@pagnylablanchecote.net']
        headers:
            from: 'no-reply@pagnylablanchecote.net'
            #X-Custom-Header: 'X-Auto-Response-Suppress', 'OOF, DR, RN, NRN, AutoReply'
            X-Custom-Header: 'X-Auto-Response-Suppress'