vich_uploader:
    db_driver: orm

    mappings:
        evenement_image: 
            uri_prefix: /images/evenements
            upload_destination: '%kernel.project_dir%/public/images/evenements'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true

        avatar_image:
            uri_prefix:         /images/evenements
            upload_destination: '%kernel.project_dir%/public/images/evenements'
            namer:              Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load:     true
            delete_on_update:   true
            delete_on_remove:   true

        event_pdf: 
            uri_prefix: /documents/events
            upload_destination: '%kernel.project_dir%/public/documents/events'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: true
            delete_on_update: true
            delete_on_remove: true
            
    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
    #        namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
