# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
    # send all emails to a specific address
    delivery_addresses: ['mairie@pagnylablanchecote.net']
    url: '%env(MAILER_URL)%'
    spool: { type: 'memory' }